


def line(katz_deli)# This file was generated by the `rspec --init` command. Conventionally, all
 if katz_deli.length == 0
   puts "The line is currently empty."
 else
   new_arr = []
   katz_deli.each_with_index{|person,index|new_arr << "#{index+1}.#{person}"}
     puts "The line is curently:#{new_arr.join('')}"# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
  end
  end
 # Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
